edition = "2024"
unstable_features = true
condense_wildcard_suffixes = true
format_code_in_doc_comments = true
hex_literal_case = "Upper"
imports_granularity = "Module"
use_field_init_shorthand = true
format_strings = true
normalize_comments = true
match_block_trailing_comma = true
hard_tabs = true
newline_style = "Unix"
